name: CI/CD
on: [push]
jobs:
  image:
    name: Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          push: always
          imageName: ghcr.io/rails-lambda/lamby-devcontainer
          cacheFrom: ghcr.io/rails-lambda/lamby-devcontainer
          runCmd: echo DONE!
  test:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup & Test
        uses: devcontainers/ci@v0.3
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/lamby-devcontainer
          env: |
            CI
          runCmd: |
            ./bin/setup
            ./bin/test
